improved schema for Greenplum

diff --git a/scripts/greenplum/setup_db b/scripts/greenplum/setup_db
--- a/scripts/greenplum/setup_db
+++ b/scripts/greenplum/setup_db
@@ -1,1 +1,10 @@
+#!/bin/bash
+
+USER=`whoami`
+
+if [ "$USER" != "gpadmin" ]; then
+        echo "ERROR: Database must be setup as user gpadmin"
+        exit 1
+fi
+
 gpinitsystem -c gpinitsystem_singlenode
