added tools to create and restore VoltDB snapshots

diff --git a/scripts/voltdb/stop_cluster b/scripts/voltdb/stop_cluster
--- a/scripts/voltdb/stop_cluster
+++ b/scripts/voltdb/stop_cluster
@@ -1,1 +1,13 @@
+#!/bin/bash
+
+# The script needs admin rights
+if [ `/usr/bin/id -u` -ne 0 ]; then
+    echo "ERROR: Run as sudo / root!"
+    exit 1
+fi
+
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+echo "Shutting down cluster"
 voltadmin shutdown
+echo "Shutdown!"
